In [1]:
from pycaret.classification import ClassificationExperiment
import pandas as pd

# 実験1

とりあえず、pycaretに入れてみる

In [4]:
df = pd.read_csv('../data/inputs/train_labeled.csv', index_col=0)
df_test = pd.read_csv('../data/inputs/test.csv', index_col=0)

s = ClassificationExperiment()
s.setup(df, target = 'labels', session_id = 123)
best = s.compare_models()

In [21]:
df_test.drop('labels', axis=1, inplace=True)
df_sub = s.predict_model(best, data=df_test)
df_sub["prediction_label"]
df_sub["prediction_label"].to_csv('../data/outputs/submission.csv')

# 実験2
クラス5は予測に使わず、クラス0-4のみで学習させてみる。予測確率が小さい下位60パーセントをクラス5とする。

In [29]:
df_train_labeled = pd.read_csv('../data/input/train_labeled.csv')
# クラス5を除外
df_train_labeled = df[df_train_labeled['labels'] != 5]

for n_components in [40, 100, 200, 400, 800, 1200, 1600, 2000]:
    s = ClassificationExperiment()
    s.setup(
        df_train_labeled,
        target = 'labels',
        session_id = 123,
        pca = True,
        pca_components=n_components,
    )

    model_list = s.compare_models(
        include = ['catboost', 'gbc', 'xgboost', 'lightgbm', 'rf'],
        n_select = 5,
    )

,,
,,
Initiated,. . . . . . . . . . . . . . . . . .,13:38:58
Status,. . . . . . . . . . . . . . . . . .,Fitting 10 Folds
Estimator,. . . . . . . . . . . . . . . . . .,Light Gradient Boosting Machine

Processing:   0%|          | 0/29 [00:00<?, ?it/s]