# KNNでpseudo labeling
- (実際はKNNでない。)
- labeledに含まれる5つのデータに近いものをラベル5として、pseudo labelingする。

In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import lightgbm as lgb
import pickle
import re
from sklearn.model_selection import StratifiedKFold

sys.path.append(os.path.abspath('..'))
from utils.process import drop_all_na_cols, drop_zero_var_cols, fillna_with_zero

In [149]:
with open('../data/output/feature_top160.pkl', 'rb') as f:
    top160_feature_names = pickle.load(f)

df_labeled_train = pd.read_csv('../data/input/train_labeled.csv', index_col=0)
df_unlabeled_train = pd.read_csv('../data/input/train_unlabeled.csv', index_col=0)
df_test = pd.read_csv('../data/input/test.csv', index_col=0)


# カラム名の正規化
df_labeled_train = df_labeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
df_unlabeled_train = df_unlabeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
df_test = df_test.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

y_labeled_train = df_labeled_train['labels'].values
df_labeled_train = df_labeled_train[top160_feature_names]
df_labeled_train.fillna(0, inplace=True)
df_labeled_train['labels'] = y_labeled_train

df_unlabeled_train = df_unlabeled_train[top160_feature_names]
df_unlabeled_train = df_unlabeled_train.fillna(0)
df_test = df_test[top160_feature_names]
df_test = df_test.fillna(0)

print(df_labeled_train.shape, df_unlabeled_train.shape, df_test.shape)

(1505, 161) (1250, 160) (1250, 160)

# それぞれのクラス5点から近い150ずつをとってきて、pseudo labeling

In [150]:
class_5_data = df_labeled_train[df_labeled_train['labels'] == 5].drop('labels', axis=1)
distances_list = []

for idx in range(5):
    distances = np.array([np.linalg.norm(
        class_5_data.iloc[idx].values - df_unlabeled_train.iloc[i].values
    ) for i in range(len(df_unlabeled_train))])
    distances_list.append(distances)

distances_list = np.array(distances_list)

df_unlabeled_train['labels'] = -1
for distances in distances_list:
    close_idx = np.argsort(distances)[:150]
    df_unlabeled_train.loc[close_idx+df_unlabeled_train.index[0], 'labels'] = 5

# クラス5にしたものをconcatして訓練

In [151]:
from pycaret.classification import ClassificationExperiment

df_class5 = df_unlabeled_train[df_unlabeled_train['labels'] == 5]
df_concat = pd.concat([df_labeled_train, df_class5], axis=0)

s = ClassificationExperiment()
s.setup(data=df_concat, 
        target='labels', 
        session_id=123)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

# unlabeledの残りをpseudo labelingして再訓練

In [152]:
df_unlabeled_train['labels'] = s.predict_model(blender, data=df_unlabeled_train)['prediction_label']
df_concat = pd.concat([df_labeled_train, df_unlabeled_train], axis=0)

s = ClassificationExperiment()
s.setup(
    df_concat,
    target='labels',
    n_jobs=-1,
)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

# 予測を保存

In [164]:
df_pred = s.predict_model(blender, data=df_test)['prediction_label']
print(df_pred.value_counts())
df_pred.to_csv('../data/output/semi_knn.csv', header=['Label'])

5    455
1    409
2    112
0    104
3     88
4     82
Name: prediction_label, dtype: int64

In [165]:
print(df_concat['labels'].value_counts().T)

1    579
5    500
3    441
4    435
0    418
2    382
Name: labels, dtype: int64

# 実験2: 1とほぼ同じ。　
- テストの分布に合わせるためにクラス1を150個とってきて、クラス5にする。

In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import lightgbm as lgb
from pycaret.classification import ClassificationExperiment
import pickle
import re
from sklearn.model_selection import StratifiedKFold

sys.path.append(os.path.abspath('..'))
from utils.process import drop_all_na_cols, drop_zero_var_cols, fillna_with_zero

# データの読み込み
with open('../data/output/feature_top160.pkl', 'rb') as f:
    top160_feature_names = pickle.load(f)

df_labeled_train = pd.read_csv('../data/input/train_labeled.csv', index_col=0)
df_unlabeled_train = pd.read_csv('../data/input/train_unlabeled.csv', index_col=0)
df_test = pd.read_csv('../data/input/test.csv', index_col=0)

# カラム名の正規化
df_labeled_train = df_labeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
df_unlabeled_train = df_unlabeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
df_test = df_test.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

y_labeled_train = df_labeled_train['labels'].values
df_labeled_train = df_labeled_train[top160_feature_names]
df_labeled_train.fillna(0, inplace=True)
df_labeled_train['labels'] = y_labeled_train

df_unlabeled_train = df_unlabeled_train[top160_feature_names]
df_unlabeled_train = df_unlabeled_train.fillna(0)
df_test = df_test[top160_feature_names]
df_test = df_test.fillna(0)

print(df_labeled_train.shape, df_unlabeled_train.shape, df_test.shape)


# クラス5と擬似ラベルの付与
class_5_data = df_labeled_train[df_labeled_train['labels'] == 5].drop('labels', axis=1)
distances_list = []

for idx in range(5):
    distances = np.array([np.linalg.norm(
        class_5_data.iloc[idx].values - df_unlabeled_train.iloc[i].values
    ) for i in range(len(df_unlabeled_train))])
    distances_list.append(distances)

distances_list = np.array(distances_list)

df_unlabeled_train['labels'] = -1
for distances in distances_list:
    close_idx = np.argsort(distances)[:150]
    df_unlabeled_train.loc[close_idx+df_unlabeled_train.index[0], 'labels'] = 5


df_class5 = df_unlabeled_train[df_unlabeled_train['labels'] == 5]
df_concat = pd.concat([df_labeled_train, df_class5], axis=0)

# モデル5の学習
s = ClassificationExperiment()
s.setup(data=df_concat, 
        target='labels', 
        session_id=123)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

(1505, 161) (1250, 160) (1250, 160)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

# 1と予測したものの中で予測確率が低い6割をクラス5にして再訓練

In [187]:
df_pseudo = s.predict_model(blender, data=df_unlabeled_train)[['prediction_label', 'prediction_score']]
threshold = df_pseudo[df_pseudo['prediction_label'] == 1]['prediction_score'].quantile(0.6)
df_pseudo['prediction_label'] = df_pseudo.apply(lambda x: 5
                            if 
                            (x['prediction_score'] < threshold  and x['prediction_label'] == 1)
                            else x['prediction_label'], axis=1)
df_pseudo.index = df_unlabeled_train.index
df_unlabeled_train['labels'] = df_pseudo['prediction_label'].astype(int)
print(df_unlabeled_train['labels'].value_counts().T)
df_concat = pd.concat([df_labeled_train, df_unlabeled_train], axis=0)
print(df_concat['labels'].value_counts().T)

s = ClassificationExperiment()
s.setup(
    df_concat,
    target='labels',
    n_jobs=-1,
)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=4, subsample_freq=0 will be ignored. Current value: bagging_freq=4
[LightGBM] [Warning] feature_fraction is set=0.9, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.9
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
5    662
3    141
4    135
0    118
1    112
2     82
Name: labels, dtype: int64
5    667
3    441
4    435
0    418
1    412
2    382
Name: labels, dtype: int64

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [189]:
df_pred = s.predict_model(blender, data=df_test)['prediction_label']
print(df_pred.value_counts())
df_pred.to_csv('../data/output/semi_knn.csv', header=['Label'])

5    612
1    257
2    110
0    101
3     87
4     83
Name: prediction_label, dtype: int64

# 実験3 2とほぼ同じ
- testを使ってpseudo labeling

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import lightgbm as lgb
from pycaret.classification import ClassificationExperiment
import pickle
import re
from sklearn.model_selection import StratifiedKFold

# データの読み込み
df_labeled_train = pd.read_csv('../data/input/train_labeled_top160.csv', index_col=0)
df_unlabeled_train = pd.read_csv('../data/input/train_unlabeled_top160.csv', index_col=0)
df_test = pd.read_csv('../data/input/test_top160.csv', index_col=0)

# カラム名の正規化
# df_labeled_train = df_labeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
# df_unlabeled_train = df_unlabeled_train.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
# df_test = df_test.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

# y_labeled_train = df_labeled_train['labels'].values
# df_labeled_train = df_labeled_train[top160_feature_names]
# df_labeled_train.fillna(0, inplace=True)
# df_labeled_train['labels'] = y_labeled_train

# df_unlabeled_train = df_unlabeled_train[top160_feature_names]
# df_unlabeled_train = df_unlabeled_train.fillna(0)
# df_test = df_test[top160_feature_names]
# df_test = df_test.fillna(0)

# df_labeled_train = pd.read_csv('../data/input/train_labeled_umap.csv', index_col=0)
# y_labeled_train = df_labeled_train['labels'].values
# df_unlabeled_train = pd.read_csv('../data/input/train_unlabeled_umap.csv', index_col=0)
# df_test = pd.read_csv('../data/input/test_umap.csv', index_col=0)

print(df_labeled_train.shape, df_unlabeled_train.shape, df_test.shape)


# クラス5と擬似ラベルの付与
class_5_data = df_labeled_train[df_labeled_train['labels'] == 5].drop('labels', axis=1)
distances_list = []

for idx in range(5):
    distances = np.array([np.linalg.norm(
        class_5_data.iloc[idx].values - df_test.iloc[i].values
    ) for i in range(len(df_unlabeled_train))])
    distances_list.append(distances)

distances_list = np.array(distances_list)

df_test['labels'] = -1
for distances in distances_list:
    close_idx = np.argsort(distances)[:150]
    df_test.loc[close_idx+df_test.index[0], 'labels'] = 5


df_class5 = df_test[df_test['labels'] == 5]
df_concat = pd.concat([df_labeled_train, df_class5], axis=0)
print(df_concat['labels'].value_counts().T)

# モデル5の学習
s = ClassificationExperiment()
s.setup(data=df_concat, 
        target='labels', 
        session_id=123)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

(1505, 161) (1250, 160) (1250, 160)
5    521
0    300
3    300
2    300
1    300
4    300
Name: labels, dtype: int64

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [ ]:
# unlabeledに擬似ラベルを付与
df_pseudo = s.predict_model(blender, data=df_unlabeled_train)[['prediction_label', 'prediction_score']]
threshold = df_pseudo[df_pseudo['prediction_label'] == 1]['prediction_score'].quantile(0.6)
df_pseudo['prediction_label'] = df_pseudo.apply(lambda x: 5
                            if 
                            (x['prediction_score'] < threshold  and x['prediction_label'] == 1)
                            else x['prediction_label'], axis=1)
df_pseudo.index = df_unlabeled_train.index
df_unlabeled_train['labels'] = df_pseudo['prediction_label'].astype(int)
print(df_unlabeled_train['labels'].value_counts().T)
df_concat = pd.concat([df_labeled_train, df_unlabeled_train], axis=0)
print(df_concat['labels'].value_counts().T)

s = ClassificationExperiment()
s.setup(
    df_concat,
    target='labels',
    n_jobs=-1,
)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
[LightGBM] [Warning] bagging_freq is set=2, subsample_freq=0 will be ignored. Current value: bagging_freq=2
[LightGBM] [Warning] feature_fraction is set=0.4, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.4
[LightGBM] [Warning] bagging_fraction is set=0.6, subsample=1.0 will be ignored. Current value: bagging_fraction=0.6
5    383
0    202
3    184
4    182
2    176
1    123
Name: labels, dtype: int64
0    502
3    484
4    482
2    476
1    423
5    388
Name: labels, dtype: int64

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [ ]:
df_pred = s.predict_model(blender, data=df_test)[['prediction_label', 'prediction_score']]

threshold = df_pred[df_pred['prediction_label'] == 1]['prediction_score'].quantile(0.6)

df_pred['Label'] = df_pred.apply(lambda x: 5
                            if 
                            (x['prediction_score'] < threshold  and x['prediction_label'] == 1)
                            else x['prediction_label'], axis=1).astype(int)

print(df_pred['Label'].value_counts())
df_pred['Label'].to_csv('../data/output/semi_knn_cali.csv', header=['Label'])

[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] feature_fraction is set=0.7, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
[LightGBM] [Warning] bagging_freq is set=0, subsample_freq=0 will be ignored. Current value: bagging_freq=0
[LightGBM] [Warning] feature_fraction is set=0.7, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.7
[LightGBM] [Warning] bagging_fraction is set=1.0, subsample=1.0 will be ignored. Current value: bagging_fraction=1.0
5    706
2    131
1    116
0    110
3    101
4     86
Name: Label, dtype: int64

# 実験4: 3とほぼ同じ
- testを使ってpseudo labeling
- umapを使う
- unlabeledで1と予測したものの中で予測確率が低い6割をクラス5にして再訓練
- 最後にtestを予測して、クラス数を調整

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import lightgbm as lgb
from pycaret.classification import ClassificationExperiment
import pickle
import re
from sklearn.model_selection import StratifiedKFold


df_labeled_train = pd.read_csv('../data/input/train_labeled_umap.csv', index_col=0)
df_unlabeled_train = pd.read_csv('../data/input/train_unlabeled_umap.csv', index_col=0)
df_test = pd.read_csv('../data/input/test_umap.csv', index_col=0)


# クラス5を抽出
class_5_data = df_labeled_train[df_labeled_train['labels'] == 5].drop('labels', axis=1)
distances_list = []

for idx in range(5):
    distances = np.array([np.linalg.norm(
        class_5_data.iloc[idx].values - df_test.iloc[i].values
    ) for i in range(len(df_unlabeled_train))])
    distances_list.append(distances)

distances_list = np.array(distances_list)

df_test['labels'] = -1
for distances in distances_list:
    close_idx = np.argsort(distances)[:100]
    df_test.loc[close_idx+df_test.index[0], 'labels'] = 5


df_class5 = df_test[df_test['labels'] == 5]
df_concat = pd.concat([df_labeled_train, df_class5], axis=0)
print(df_concat['labels'].value_counts().T)

# モデル5の学習
s = ClassificationExperiment()
s.setup(data=df_labeled_train, 
        target='labels', 
        session_id=123)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

5    406
0    300
3    300
2    300
1    300
4    300
Name: labels, dtype: int64

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [21]:
df_pseudo = s.predict_model(blender, data=df_unlabeled_train)[['prediction_label', 'prediction_score']]
print(df_pseudo['prediction_label'].value_counts().T)
threshold = df_pseudo[df_pseudo['prediction_label'] == 1]['prediction_score'].quantile(0.4)
df_pseudo['prediction_label'] = df_pseudo.apply(lambda x: 5
                            if 
                            (x['prediction_score'] < threshold  and x['prediction_label'] == 1)
                            else x['prediction_label'], axis=1)

threshold = df_pseudo[df_pseudo['prediction_label'] == 4]['prediction_score'].quantile(0.2)
df_pseudo['prediction_label'] = df_pseudo.apply(lambda x: 5
                            if 
                            (x['prediction_score'] < threshold  and x['prediction_label'] == 4)
                            else x['prediction_label'], axis=1)

df_pseudo.index = df_unlabeled_train.index
df_unlabeled_train['labels'] = df_pseudo['prediction_label'].astype(int)
print(df_unlabeled_train['labels'].value_counts().T)
df_concat = pd.concat([df_labeled_train, df_unlabeled_train], axis=0)
print(df_concat['labels'].value_counts().T)

s = ClassificationExperiment()
s.setup(
    df_concat,
    target='labels',
    n_jobs=-1,
)

model_list = [s.create_model(model) 
              for model 
              in ['lightgbm', 'xgboost', 'rf', 'et']]
tuned_model_list = [s.tune_model(model, optimize='f1') for model in model_list]
blender = s.blend_models(tuned_model_list)

[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7
[LightGBM] [Warning] bagging_freq is set=6, subsample_freq=0 will be ignored. Current value: bagging_freq=6
[LightGBM] [Warning] feature_fraction is set=0.5, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.5
[LightGBM] [Warning] bagging_fraction is set=0.7, subsample=1.0 will be ignored. Current value: bagging_fraction=0.7
1    341
4    274
2    228
0    201
3    195
5     11
Name: prediction_label, dtype: int64
2    228
4    219
1    205
5    202
0    201
3    195
Name: labels, dtype: int64
2    528
4    519
1    505
0    501
3    495
5    207
Name: labels, dtype: int64

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [22]:
df_pred = s.predict_model(blender, data=df_test)[['prediction_label', 'prediction_score']]

# threshold = df_pred[df_pred['prediction_label'] == 1]['prediction_score'].quantile(0.7)

# df_pred['prediction_label'] = df_pred.apply(lambda x: 5
#                             if 
#                             (x['prediction_score'] < threshold  and x['prediction_label'] == 1)
#                             else x['prediction_label'], axis=1).astype(int)
        
# threshold = df_pred[df_pred['prediction_label'] == 4]['prediction_score'].quantile(0.7)
            
# df_pred['prediction_label'] = df_pred.apply(lambda x: 5
#                             if 
#                             (x['prediction_score'] < threshold  and x['prediction_label'] == 4)
#                             else x['prediction_label'], axis=1).astype(int)

# threshold = df_pred[df_pred['prediction_label'] == 2]['prediction_score'].quantile(0.5)
            
# df_pred['prediction_label'] = df_pred.apply(lambda x: 5
#                             if 
#                             (x['prediction_score'] < threshold  and x['prediction_label'] == 2)
#                             else x['prediction_label'], axis=1).astype(int)

print(df_pred['prediction_label'].value_counts())
df_pred['prediction_label'].to_csv('../data/output/semi_knn_cali_umap.csv', header=['Label'])

1    337
5    276
2    219
4    188
0    123
3    107
Name: prediction_label, dtype: int64